/*
 * Este proyecto pertenece a Martín Alejandro Fernández.
 * Cualquier edición del siguiente archivo, sin autorización
 * no esta permitida.
 */

package lib;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Martín Alejandro Fernández
 */
public class Menu extends javax.swing.JFrame {
    private int NivelDificultad=1;
    private int NivelActual=1;
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        ImageIcon icono = new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"));
        Image imagen = icono.getImage();
        ImageIcon iconoEscalado = new ImageIcon (imagen.getScaledInstance(350,250,Image.SCALE_SMOOTH));
        jlblFondo.setIcon(iconoEscalado);
        this.jlblNivelActual.setText("Nivel "+this.NivelActual);
        this.jlblDificultad.setText("Dificultad "+this.NivelDificultad);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblJuegoNuevo = new javax.swing.JLabel();
        jlblCreditos = new javax.swing.JLabel();
        jlblSalir = new javax.swing.JLabel();
        jlblDificultad = new javax.swing.JLabel();
        jlblTitulo = new javax.swing.JLabel();
        jlblNivelActual = new javax.swing.JLabel();
        jlblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cazador de Almas");
        setBackground(new java.awt.Color(255, 0, 0));
        setName("frmMenu"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblJuegoNuevo.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jlblJuegoNuevo.setForeground(new java.awt.Color(255, 255, 255));
        jlblJuegoNuevo.setText("Juego Nuevo");
        jlblJuegoNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblJuegoNuevoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlblJuegoNuevoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlblJuegoNuevoMouseExited(evt);
            }
        });
        getContentPane().add(jlblJuegoNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jlblCreditos.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jlblCreditos.setForeground(new java.awt.Color(255, 255, 255));
        jlblCreditos.setText("Créditos");
        jlblCreditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblCreditosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlblCreditosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlblCreditosMouseExited(evt);
            }
        });
        getContentPane().add(jlblCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jlblSalir.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jlblSalir.setForeground(new java.awt.Color(255, 255, 255));
        jlblSalir.setText("Salir");
        jlblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlblSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlblSalirMouseExited(evt);
            }
        });
        getContentPane().add(jlblSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        jlblDificultad.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jlblDificultad.setForeground(new java.awt.Color(255, 255, 255));
        jlblDificultad.setText("Dificultad 1");
        jlblDificultad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblDificultadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlblDificultadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlblDificultadMouseExited(evt);
            }
        });
        getContentPane().add(jlblDificultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jlblTitulo.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jlblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jlblTitulo.setText("Cazador de Almas");
        jlblTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblTituloMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlblTituloMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlblTituloMouseExited(evt);
            }
        });
        getContentPane().add(jlblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jlblNivelActual.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jlblNivelActual.setForeground(new java.awt.Color(255, 255, 255));
        jlblNivelActual.setText("Nivel 1");
        jlblNivelActual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblNivelActualMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlblNivelActualMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlblNivelActualMouseExited(evt);
            }
        });
        getContentPane().add(jlblNivelActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jlblFondo.setBackground(new java.awt.Color(153, 153, 153));
        jlblFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblFondo.setText("fondo");
        jlblFondo.setOpaque(true);
        getContentPane().add(jlblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlblJuegoNuevoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblJuegoNuevoMouseEntered
        this.jlblJuegoNuevo.setForeground(Color.RED);
    }//GEN-LAST:event_jlblJuegoNuevoMouseEntered

    private void jlblJuegoNuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblJuegoNuevoMouseExited
        this.jlblJuegoNuevo.setForeground(Color.WHITE);
        Sonido.FxMenuSplat.play();
    }//GEN-LAST:event_jlblJuegoNuevoMouseExited

    private void jlblCreditosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblCreditosMouseEntered
        this.jlblCreditos.setForeground(Color.RED);
    }//GEN-LAST:event_jlblCreditosMouseEntered

    private void jlblCreditosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblCreditosMouseExited
        this.jlblCreditos.setForeground(Color.WHITE);
        Sonido.FxMenuSplat.play();
    }//GEN-LAST:event_jlblCreditosMouseExited

    private void jlblSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblSalirMouseEntered
        this.jlblSalir.setForeground(Color.RED);
    }//GEN-LAST:event_jlblSalirMouseEntered

    private void jlblSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblSalirMouseExited
        this.jlblSalir.setForeground(Color.WHITE);
        Sonido.FxMenuSplat.play();
    }//GEN-LAST:event_jlblSalirMouseExited

    private void jlblDificultadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblDificultadMouseEntered
        this.jlblDificultad.setForeground(Color.RED);
    }//GEN-LAST:event_jlblDificultadMouseEntered

    private void jlblDificultadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblDificultadMouseExited
        this.jlblDificultad.setForeground(Color.WHITE);
        Sonido.FxMenuSplat.play();
    }//GEN-LAST:event_jlblDificultadMouseExited

    private void jlblJuegoNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblJuegoNuevoMouseClicked
        //ñlñlñ
        if(CONSTANTES.MENSAJE_CONSOLA){System.out.println("Creando interfase");}
        JFrame Interfase=new JFrame();
                
        if(CONSTANTES.MENSAJE_CONSOLA){System.out.println("Cargando Juego");}
         
        String Nombre="";
        Nombre=JOptionPane.showInputDialog(Interfase, "Ingrese su Nombre");
        if(Nombre.isEmpty()){
            Nombre="Alex";
        }
        
        if(!Nombre.isEmpty()){
            Juego NuevoJuego=new Juego(Interfase, Nombre);
            int mNivel=this.NivelActual;//1;//Integer.parseInt(args[0]);
            int mDificultad=this.NivelDificultad;//this.jComboBox1.getSelectedIndex();//Juego.DIFICULTAD_MAXIMA;//Integer.parseInt(args[1]);

            if(mNivel>=0&&mDificultad>=0){NuevoJuego.NuevoNivel(mNivel,mDificultad);}
            else{NuevoJuego.NuevoNivel(0,Juego.DIFICULTAD_MAXIMA);}

            Interfase.add(NuevoJuego);
            NuevoJuego.PrepararVentana(Interfase);
            NuevoJuego.MostrarVentana(Interfase);
            Interfase.setLocationRelativeTo(this);


            if(CONSTANTES.MENSAJE_CONSOLA){System.out.println("Arrancando el juego");}
            NuevoJuego.CorrerJuego();
            Thread ThreadJuego=new Thread(NuevoJuego,"Hilo De Juego");
            ThreadJuego.start();
        }
    }//GEN-LAST:event_jlblJuegoNuevoMouseClicked

    private void jlblCreditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblCreditosMouseClicked
        String Mensaje="Martín Alejandro Fernández (c) 2015";
        Mensaje+="\nJuego desarrollado para apoyar el aprendizaje del lenguaje de programación Java";
        Mensaje+="\nConceptos Involucrados:";
        Mensaje+="\nProgramación Orientada a Objetos.";
        Mensaje+="\nManejo de Tipos de datos nativos.";
        Mensaje+="\nManejo de Tipos de datos envoltorios.";
        Mensaje+="\nManejo de ArrayList y Arreglos Multidimensionales.";
        Mensaje+="\nManejo de Threads.";
        Mensaje+="\nMultimedia básica.";
        JOptionPane.showMessageDialog(this, Mensaje, "Cazador de Almas V1.0", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jlblCreditosMouseClicked

    private void jlblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblSalirMouseClicked
        Sonido.FxMenuSalir.play();
        this.dispose();
    }//GEN-LAST:event_jlblSalirMouseClicked

    private void jlblDificultadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblDificultadMouseClicked
        this.NivelDificultad=(this.NivelDificultad%3)+1;
        this.jlblDificultad.setText("Dificultad "+this.NivelDificultad);
    }//GEN-LAST:event_jlblDificultadMouseClicked

    private void jlblTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblTituloMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblTituloMouseClicked

    private void jlblTituloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblTituloMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblTituloMouseEntered

    private void jlblTituloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblTituloMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblTituloMouseExited

    private void jlblNivelActualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblNivelActualMouseClicked
        this.NivelActual=(this.NivelActual%6)+1;
        this.jlblNivelActual.setText("Nivel "+this.NivelActual);
    }//GEN-LAST:event_jlblNivelActualMouseClicked

    private void jlblNivelActualMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblNivelActualMouseEntered
        this.jlblNivelActual.setForeground(Color.RED);
    }//GEN-LAST:event_jlblNivelActualMouseEntered

    private void jlblNivelActualMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblNivelActualMouseExited
        this.jlblNivelActual.setForeground(Color.WHITE);
    }//GEN-LAST:event_jlblNivelActualMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlblCreditos;
    private javax.swing.JLabel jlblDificultad;
    private javax.swing.JLabel jlblFondo;
    private javax.swing.JLabel jlblJuegoNuevo;
    private javax.swing.JLabel jlblNivelActual;
    private javax.swing.JLabel jlblSalir;
    private javax.swing.JLabel jlblTitulo;
    // End of variables declaration//GEN-END:variables
}
